// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pav-dev98/pm-auth-svc/internal/application/ports (interfaces: AuthRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/auth_repository.go -package=mocks . AuthRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/pav-dev98/pm-auth-svc/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthRepository) Create(cred *domain.AuthCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthRepositoryMockRecorder) Create(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthRepository)(nil).Create), cred)
}

// FindByEmail mocks base method.
func (m *MockAuthRepository) FindByEmail(email string) (*domain.AuthCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*domain.AuthCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockAuthRepositoryMockRecorder) FindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockAuthRepository)(nil).FindByEmail), email)
}

// FindSession mocks base method.
func (m *MockAuthRepository) FindSession(token string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSession", token)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSession indicates an expected call of FindSession.
func (mr *MockAuthRepositoryMockRecorder) FindSession(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSession", reflect.TypeOf((*MockAuthRepository)(nil).FindSession), token)
}

// RevokeSession mocks base method.
func (m *MockAuthRepository) RevokeSession(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockAuthRepositoryMockRecorder) RevokeSession(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockAuthRepository)(nil).RevokeSession), token)
}

// SaveSession mocks base method.
func (m *MockAuthRepository) SaveSession(session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockAuthRepositoryMockRecorder) SaveSession(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockAuthRepository)(nil).SaveSession), session)
}
